# -*- coding: utf-8 -*-
"""CNN_images_classification2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6F6_6jvWp59r-a0ezsN_7QOxWvTM6v3
"""

# 할당받은 GPU 확인
!nvidia-smi

import os
import random
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from PIL import Image
import math
import shutil

# PyTorch 관련
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models

# 3. Device 설정 (GPU 가속 확인)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"사용 중인 디바이스: {device}")
if device.type == 'cuda':
    print(f"GPU 모델명: {torch.cuda.get_device_name(0)}")

# 현재 Colab이 제공한 CPU 코어 수 확인
num_cpu_cores = os.cpu_count()
print(f"사용 가능한 CPU 코어 수: {num_cpu_cores}개")

# 4. 재현성을 위한 시드 고정
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)
print("초기 설정 완료")

# 데이터셋 압축 풀기
!unzip /content/drive/MyDrive/dataset_resized2.zip

# 1. 경로 설정
DATA_PATH = '/content'
BATCH_SIZE = 64  # Pro+ A100/V100 기준

# 2. 데이터셋 로드 설정
# 이미 리사이징을 하셨더라도, 텐서 변환(ToTensor)과 정규화(Normalize)는 필수.
# (Resize는 혹시 모를 에러 방지용으로 224 고정)
transform_config = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

image_datasets = {
    x: datasets.ImageFolder(os.path.join(DATA_PATH, x), transform_config)
    for x in ['train', 'valid', 'test']
}

dataloaders = {
    x: DataLoader(image_datasets[x], batch_size=BATCH_SIZE, shuffle=(x == 'train'), num_workers=8, pin_memory=True)
    for x in ['train', 'valid', 'test']
}

class_names = image_datasets['train'].classes
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"데이터 경로: {DATA_PATH}")
print(f"인식된 클래스({len(class_names)}개): {class_names}")

# 3. 사전 학습된 EfficientNetV2-S 모델 불러오기
# weights='DEFAULT'는 가장 성능이 좋은 가중치(IMAGENET1K_V1)를 자동으로 가져옴.
model = models.efficientnet_v2_s(weights='DEFAULT')

# 4. 전이학습 설정: Feature Extractor 부분 파라미터 고정 (Freezing)
# 초기 학습 시에는 기존의 잘 학습된 특징 추출 능력을 망치지 않기 위해 고정.
# 데이터가 충분히 많다면 풀고 학습해도 되지만, 일단 안전하게 고정하고 시작하는 것을 추천.
for param in model.features.parameters():
    param.requires_grad = False

# 5. 분류기(Classifier) 교체
# EfficientNetV2의 마지막 층(classifier)은 원래 1000개를 분류하게 되어 있음.
# 이것을 데이터셋의 클래스 개수(11개)로 바꿔줌.

num_ftrs = model.classifier[1].in_features # 들어오는 특징 개수 확인 (1280개)

model.classifier = nn.Sequential(
    nn.Dropout(p=0.2, inplace=True), # 과적합 방지
    nn.Linear(num_ftrs, len(class_names)) # 1280 -> 11 (우리의 클래스 개수)
)

# 6. 모델을 GPU로 이동 및 학습 설정
model = model.to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.classifier.parameters(), lr=0.001)

print("모델 설정 완료: EfficientNetV2-S")
print(f"출력 클래스 개수: {len(class_names)}개 ({class_names})")

"""전이학습 시작"""

# --- 학습 루프 실행 ---
import time
import copy

print("\n--- 전이학습 시작 ---")
EPOCHS = 10

best_model_wts = copy.deepcopy(model.state_dict())
best_acc = 0.0

for epoch in range(EPOCHS):
    for phase in ['train', 'valid']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_corrects = 0

        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_corrects += torch.sum(preds == labels.data)

        epoch_acc = running_corrects.double() / len(image_datasets[phase])

        # 정확도 출력
        print(f"Epoch {epoch+1}/{EPOCHS} - [{phase}] Acc: {epoch_acc:.4f}")

        # 검증일 때만 최고 모델 저장
        if phase == 'valid':
            if epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())

print(f"학습 완료! 최고 검증 정확도: {best_acc:.4f}")
model.load_state_dict(best_model_wts) # 최고 성능 모델 로드

# --- [1] 평가 함수 정의 ---
def evaluate_model(model, dataloader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad(): # 기록하지 않음 (메모리 절약)
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    accuracy = correct / total
    return accuracy

# --- [2] Test 데이터로 최종 성능 확인 ---
print("\n--- [최종 테스트] 모델 성능 평가 ---")

test_acc = evaluate_model(model, dataloaders['test'])
print(f'최종 테스트 정확도(Test Acc): {test_acc:.4f}')

"""최종 Test 데이터 정확도 확인"""

# Test 데이터셋으로 최종 성능 평가
print("--- 최종 Test 데이터 평가 시작 ---")

model.eval() # 평가 모드 (필수)
correct = 0
total = 0

with torch.no_grad(): # 기울기 계산 끔 (메모리 절약)
  for inputs, labels in dataloaders['test']:
    inputs = inputs.to(device)
    labels = labels.to(device)

    outputs = model(inputs)
    _, predicted = torch.max(outputs, 1)

    total += labels.size(0)
    correct += (predicted == labels).sum().item()

test_acc = 100 * correct / total
print(f"최종 Test 정확도: {test_acc:.2f}%")

"""시각화"""

def visualize_model(model, num_images=6):
    old_mode = model.training
    model.eval()
    images_so_far = 0
    fig = plt.figure(figsize=(15, 10))

    with torch.no_grad():
        for i, (inputs, labels) in enumerate(dataloaders['test']):
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            for j in range(inputs.size(0)):
                images_so_far += 1
                ax = plt.subplot(num_images//2, 2, images_so_far)
                ax.axis('off')

                # 예측 결과 vs 정답
                predicted_label = class_names[preds[j]]
                true_label = class_names[labels[j]]

                color = 'blue' if predicted_label == true_label else 'red'
                ax.set_title(f'Pred: {predicted_label} | True: {true_label}', color=color)

                # 이미지 출력 (Tensor -> Image 변환 및 정규화 해제)
                inp = inputs.cpu().data[j].numpy().transpose((1, 2, 0))
                mean = np.array([0.485, 0.456, 0.406])
                std = np.array([0.229, 0.224, 0.225])
                inp = std * inp + mean
                inp = np.clip(inp, 0, 1)
                plt.imshow(inp)

                if images_so_far == num_images:
                    model.train(mode=old_mode)
                    return
        model.train(mode=old_mode)

# 실행 (이미지 6개 보여줌)
visualize_model(model, num_images=6)

def plot_confusion_matrix(model, dataloader):
    # 1. 모든 데이터에 대해 예측값과 정답 수집
    y_true = []
    y_pred = []

    model.eval() # 평가 모드

    print("데이터 예측 중...", end="")
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device) # CPU 연산을 위해 굳이 안 보내도 되지만 통일성 유지

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            # Tensor를 CPU로 가져와서 리스트에 추가
            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())
    print(" 완료!")

    # 2. Confusion Matrix 계산
    # y_true: 실제 정답, y_pred: 모델의 예측
    cm = confusion_matrix(y_true, y_pred)

    # 3. 시각화를 위한 DataFrame 생성 (라벨 이름 포함)
    df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)

    # 4. 히트맵 그리기
    plt.figure(figsize=(10, 8))
    sns.heatmap(df_cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    # annot=True: 숫자 표시, fmt='d': 정수형(소수점 제거), cmap='Blues': 파란색 계열

    plt.title('Confusion Matrix (EfficientNetV2-S)', fontsize=15)
    plt.ylabel('True Label (Actual)', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    plt.xticks(rotation=45) # x축 글씨 겹치지 않게 기울임
    plt.show()

# 실행 (Test 데이터셋 사용)
plot_confusion_matrix(model, dataloaders['test'])

"""Classification Report"""

def get_detailed_report(model, dataloader):
    y_true = []
    y_pred = []

    model.eval()
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 정밀도, 재현율, F1-score 출력
    print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

print("--- 클래스별 상세 성적표 (F1-Score) ---")
get_detailed_report(model, dataloaders['test'])

"""Grad-CAM"""

# 1. 라이브러리 설치
!pip install grad-cam

import cv2
from pytorch_grad_cam import GradCAM

def visualize_gradcam_unfreeze(model, num_images=4):
    # 1. 타겟 레이어 설정 (EfficientNetV2의 마지막 블록)
    # [중요] 특정 Conv2d 하나만 찝는 것보다 마지막 블록 전체를 주는 게 더 안정적입니다.
    target_layers = [model.features[-1]]

    # ★★★ [핵심 해결책] ★★★
    # 해당 레이어의 기울기 계산을 강제로 켭니다. (이거 안 하면 Grad-CAM 안 나옴)
    for param in model.features[-1].parameters():
        param.requires_grad = True

    model.eval()

    # 2. Grad-CAM 객체 생성
    cam = GradCAM(model=model, target_layers=target_layers)

    # 테스트 데이터 로드
    data_iter = iter(dataloaders['test'])
    images, labels = next(data_iter)
    images = images.to(device)

    fig, axes = plt.subplots(1, num_images, figsize=(15, 5))
    print("Grad-CAM 분석 중... (Frozen Layer 해제 완료)")

    for i in range(num_images):
        try:
            input_tensor = images[i].unsqueeze(0)

            # 3. Grad-CAM 생성
            grayscale_cam = cam(input_tensor=input_tensor, targets=None)

            # 결과가 비어있는지 체크
            if grayscale_cam is None or grayscale_cam.size == 0:
                print(f"이미지 {i}: CAM 생성 실패 (Gradient 문제)")
                continue

            grayscale_cam = grayscale_cam[0, :]

            # 4. 이미지 준비
            img = images[i].cpu().permute(1, 2, 0).numpy()
            img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img = np.clip(img, 0, 1)

            # 5. 수동 오버레이 (OpenCV)
            heatmap = cv2.resize(grayscale_cam, (img.shape[1], img.shape[0]))
            heatmap = np.uint8(255 * heatmap)
            heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
            heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
            heatmap = np.float32(heatmap) / 255

            visualization = 0.6 * img + 0.4 * heatmap
            visualization = np.clip(visualization, 0, 1)

            # 6. 출력
            outputs = model(input_tensor)
            _, preds = torch.max(outputs, 1)
            pred_label = class_names[preds.item()]
            true_label = class_names[labels[i].item()]

            if num_images > 1:
                ax = axes[i]
            else:
                ax = axes

            ax.imshow(visualization)
            color = 'blue' if pred_label == true_label else 'red'
            ax.set_title(f"True: {true_label}\nPred: {pred_label}", color=color)
            ax.axis('off')

        except Exception as e:
            print(f"이미지 {i} 처리 실패: {e}")
            import traceback
            traceback.print_exc()

    plt.tight_layout()
    plt.show()

# 실행
visualize_gradcam_unfreeze(model, num_images=4)

""""가장 뻔뻔한 오답" 분석 (Worst Offenders)"""

import torch.nn.functional as F

def show_worst_errors(model, dataloader, num_show=6):
    wrong_examples = []

    model.eval()
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            probs = F.softmax(outputs, dim=1) # 확률로 변환
            max_probs, preds = torch.max(probs, 1)

            # 틀린 것만 수집
            wrong_indices = (preds != labels).nonzero(as_tuple=True)[0]

            for idx in wrong_indices:
                wrong_examples.append({
                    'img': inputs[idx].cpu(),
                    'true_label': class_names[labels[idx].item()],
                    'pred_label': class_names[preds[idx].item()],
                    'conf': max_probs[idx].item() # 확신도 (Confidence)
                })

    # 확신도(conf)가 높은 순서대로 정렬 (가장 뻔뻔하게 틀린 순)
    wrong_examples.sort(key=lambda x: x['conf'], reverse=True)

    print(f"총 오답 개수: {len(wrong_examples)}개")
    print(f"가장 확신에 차서 틀린 상위 {num_show}개를 보여줍니다.")

    # 시각화
    fig = plt.figure(figsize=(15, 10))
    for i in range(min(num_show, len(wrong_examples))):
        ex = wrong_examples[i]

        ax = plt.subplot(2, 3, i+1)
        img = ex['img'].permute(1, 2, 0).numpy()
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img = np.clip(img, 0, 1)

        plt.imshow(img)
        plt.title(f"True: {ex['true_label']} -> Pred: {ex['pred_label']}\nConf: {ex['conf']*100:.2f}%", color='red')
        plt.axis('off')

show_worst_errors(model, dataloaders['test'])

# 뻔뻔한 오답 + Grad-CAM 시각화

def visualize_worst_errors_with_gradcam(model, dataloader, num_show=6):
    # 1. Grad-CAM 준비 (마지막 레이어 Unfreeze)
    target_layers = [model.features[-1]]
    for param in model.features[-1].parameters():
        param.requires_grad = True

    cam = GradCAM(model=model, target_layers=target_layers)

    wrong_examples = []
    model.eval()

    print("1. 오답 데이터 수집 중...")

    # 2. 전체 데이터에서 오답 수집
    # (주의: 메모리 절약을 위해 틀린 것만 저장)
    for inputs, labels in dataloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        # 순전파
        outputs = model(inputs)
        probs = F.softmax(outputs, dim=1)
        max_probs, preds = torch.max(probs, 1)

        # 틀린 인덱스 찾기
        wrong_indices = (preds != labels).nonzero(as_tuple=True)[0]

        for idx in wrong_indices:
            wrong_examples.append({
                'input_tensor': inputs[idx].cpu(), # 나중에 GPU로 다시 보냄
                'true_label': class_names[labels[idx].item()],
                'pred_label': class_names[preds[idx].item()],
                'conf': max_probs[idx].item()
            })

    # 오답이 하나도 없으면 종료
    if len(wrong_examples) == 0:
        print("와우! 틀린 데이터가 하나도 없습니다. (정확도 100%)")
        return

    # 3. 확신도(Confidence) 높은 순 정렬
    wrong_examples.sort(key=lambda x: x['conf'], reverse=True)

    print(f"총 오답 개수: {len(wrong_examples)}개")
    print(f"그 중 가장 뻔뻔한 오답 상위 {num_show}개를 분석합니다.")

    # 4. 시각화 루프
    num_show = min(num_show, len(wrong_examples))
    rows = (num_show + 1) // 2
    fig = plt.figure(figsize=(15, 5 * rows))

    for i in range(num_show):
        ex = wrong_examples[i]

        # 텐서 준비 (GPU로 이동)
        input_tensor = ex['input_tensor'].unsqueeze(0).to(device)

        # Grad-CAM 생성 (예측한 클래스 기준)
        grayscale_cam = cam(input_tensor=input_tensor, targets=None)
        grayscale_cam = grayscale_cam[0, :]

        # 이미지 복원 (Denormalization)
        img = ex['input_tensor'].permute(1, 2, 0).numpy()
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img = np.clip(img, 0, 1)

        # 히트맵 오버레이 (OpenCV)
        heatmap = cv2.resize(grayscale_cam, (img.shape[1], img.shape[0]))
        heatmap = np.uint8(255 * heatmap)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
        heatmap = np.float32(heatmap) / 255

        visualization = 0.6 * img + 0.4 * heatmap
        visualization = np.clip(visualization, 0, 1)

        # 서브플롯 그리기
        ax = plt.subplot(rows, 3, i+1)
        ax.imshow(visualization)

        # 제목 설정 (빨간색)
        title_text = (f"True: {ex['true_label']} / Pred: {ex['pred_label']}\n"
                      f"Confidence: {ex['conf']*100:.2f}%")
        ax.set_title(title_text, color='red', fontsize=12, fontweight='bold')
        ax.axis('off')

    plt.tight_layout()
    plt.show()

# 실행
visualize_worst_errors_with_gradcam(model, dataloaders['test'], num_show=6)

"""특정 오답(Buildings → Street) 집중 분석 코드"""

def visualize_specific_confusion_fixed(model, dataloader, true_name, pred_name, num_show=6):
    # 1. 클래스 인덱스 찾기
    try:
        true_idx = class_names.index(true_name)
        pred_idx = class_names.index(pred_name)
    except ValueError:
        print(f"Error: 클래스 이름을 다시 확인해주세요.")
        return

    print(f"분석 시작: True({true_name}) -> Pred({pred_name})")

    # 2. Grad-CAM 준비
    target_layers = [model.features[-1]]
    for param in model.features[-1].parameters():
        param.requires_grad = True
    cam = GradCAM(model=model, target_layers=target_layers)

    specific_errors = []
    model.eval()

    # 3. 데이터 탐색
    for inputs, labels in dataloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        # 순전파
        outputs = model(inputs)

        # ★ [수정된 부분] Softmax를 먼저 거쳐서 0~1 사이 확률로 만듭니다.
        probs = F.softmax(outputs, dim=1)

        # ★ [수정된 부분] 원본 점수(outputs)가 아니라 확률(probs)에서 최대값을 찾습니다.
        max_probs, preds = torch.max(probs, 1)

        # 필터링: (정답 == true_name) AND (예측 == pred_name)
        mask = (labels == true_idx) & (preds == pred_idx)
        error_indices = mask.nonzero(as_tuple=True)[0]

        for idx in error_indices:
            specific_errors.append({
                'input_tensor': inputs[idx].cpu(),
                'conf': max_probs[idx].item() # 이제 정상적인 0.xx 값이 들어갑니다.
            })

    print(f"검색 결과: 총 {len(specific_errors)}장의 오답 발견.")

    if len(specific_errors) == 0:
        print("해당하는 오답이 없습니다.")
        return

    # 4. 확신도 높은 순 정렬
    specific_errors.sort(key=lambda x: x['conf'], reverse=True)

    # 5. 시각화
    # num_show 개수만큼만 보여줍니다 (기본 6개)
    num_show = len(specific_errors)
    rows = (num_show + 1) // 2
    if rows == 0: rows = 1

    fig = plt.figure(figsize=(15, 6 * rows))

    for i in range(num_show):
        ex = specific_errors[i]

        input_tensor = ex['input_tensor'].unsqueeze(0).to(device)

        # Grad-CAM 생성
        grayscale_cam = cam(input_tensor=input_tensor, targets=None)[0, :]

        # 이미지 복원
        img = ex['input_tensor'].permute(1, 2, 0).numpy()
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img = np.clip(img, 0, 1)

        # 히트맵
        heatmap = cv2.resize(grayscale_cam, (img.shape[1], img.shape[0]))
        heatmap = np.uint8(255 * heatmap)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
        heatmap = np.float32(heatmap) / 255

        visualization = 0.6 * img + 0.4 * heatmap
        visualization = np.clip(visualization, 0, 1)

        # 출력
        ax = plt.subplot(rows, 4, i+1)
        ax.imshow(visualization)

        # 제목 (이제 %가 정상적으로 나옵니다)
        title = (f"True: {true_name} -> Pred: {pred_name}\n"
                 f"Confidence: {ex['conf']*100:.2f}%")
        ax.set_title(title, color='red', fontsize=14, fontweight='bold')
        ax.axis('off')

    plt.tight_layout()
    plt.show()

# --- 실행 ---
visualize_specific_confusion_fixed(model, dataloaders['test'],
                                   true_name='buildings',
                                   pred_name='street',
                                   )

visualize_specific_confusion_fixed(model, dataloaders['test'],
                                   true_name='street',
                                   pred_name='buildings',
                                   )

visualize_specific_confusion_fixed(model, dataloaders['test'],
                                   true_name='culture',
                                   pred_name='parks',
                                   )

visualize_specific_confusion_fixed(model, dataloaders['test'],
                                   true_name='parks',
                                   pred_name='culture',
                                   num_show=6)

"""오분류된 이미지(Misclassified Images)를 추출하고 시각화

    1) valid
"""

import matplotlib.pyplot as plt
import torch
import numpy as np
import math
import os

def visualize_specific_errors(model, dataloader, class_names, target_pairs):
    """
    특정 오분류 케이스를 모두 찾아서 파일명과 함께 시각화하는 함수
    """
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # 데이터셋 원본 (파일 경로 접근용)
    dataset = dataloader.dataset

    # 수집된 오분류 데이터를 담을 리스트
    collected_errors = []

    print(f"분석 시작... (Target: {target_pairs})")

    # 배치 단위가 아니라 인덱스로 접근 (파일명 매칭을 정확히 하기 위해)
    current_idx = 0

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            batch_size = inputs.size(0)

            # 틀린 것 찾기
            not_matches = (preds != labels)

            # 틀린 인덱스(배치 내부) 추출
            error_batch_indices = np.where(not_matches.cpu().numpy())[0]

            for local_idx in error_batch_indices:
                global_idx = current_idx + local_idx

                true_idx = labels[local_idx].item()
                pred_idx = preds[local_idx].item()

                true_label = class_names[true_idx]
                pred_label = class_names[pred_idx]

                # 우리가 원하는 타겟 쌍인지 확인
                if (true_label, pred_label) in target_pairs:

                    # 파일 경로 가져오기 (ImageFolder 사용 가정)
                    # valid loader는 shuffle=False여야 정확한 매칭이 됩니다.
                    full_path = dataset.samples[global_idx][0]
                    filename = os.path.basename(full_path)

                    # 이미지 데이터 준비 (시각화용)
                    img_tensor = inputs[local_idx].cpu()

                    collected_errors.append({
                        'img_tensor': img_tensor,
                        'true': true_label,
                        'pred': pred_label,
                        'filename': filename
                    })

            current_idx += batch_size

    print(f"총 {len(collected_errors)}장의 오분류 이미지를 발견했습니다.")
    return collected_errors

def plot_errors_simple(data, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]):
    """
    수집된 데이터를 시각화 (파일명 포함)
    """
    if not data:
        print("해당 조건의 오분류가 없습니다.")
        return

    num_images = len(data)
    cols = 4
    # 이미지가 많을 경우를 대비해 행(Row) 수를 넉넉히 계산
    rows = math.ceil(num_images / cols)

    # 그림판 크기를 데이터 양에 맞춰 조절 (세로로 길게)
    plt.figure(figsize=(20, 5 * rows))

    for i, item in enumerate(data):
        ax = plt.subplot(rows, cols, i + 1)

        # Denormalize (색상 복구)
        img = item['img_tensor'].numpy().transpose((1, 2, 0))
        img = std * img + mean
        img = np.clip(img, 0, 1)

        plt.imshow(img)

        # 제목 설정 (중요: 파일명 표시)
        title_text = f"True: {item['true']} → Pred: {item['pred']}\nFile: {item['filename']}"
        plt.title(title_text, color='red', fontsize=12, fontweight='bold')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

# ================= 실행 설정 =================

# 1. 타겟 정의 (4가지 경우)
target_pairs_list = [
    ('buildings', 'street'),
    ('street', 'buildings'),
    ('parks', 'culture'),
    ('culture', 'parks')
]

# 2. 실행 (valid loader 사용)
# shuffle=False 상태인 dataloaders['valid']를 넣어야 파일명이 정확합니다.
errors = visualize_specific_errors(
    model,
    dataloaders['valid'],
    class_names,
    target_pairs_list
)

# 3. 시각화 출력
plot_errors_simple(errors)

import os

def find_misclassified_filenames(model, dataset, class_names, target_pair=None):
    """
    오분류된 이미지의 '파일명(경로)'을 찾아내는 함수
    주의: ImageFolder를 사용했다고 가정합니다 (dataset.samples에 경로가 있음)
    """
    model.eval()
    print(f"-------- 검사 시작: {target_pair if target_pair else '전체'} --------")

    # 데이터셋을 하나씩 순회 (DataLoader가 아니라 Dataset 자체를 순회해야 파일명을 알기 쉬움)
    # 속도를 위해 GPU 사용
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    count = 0

    with torch.no_grad():
        for i in range(len(dataset)):
            # 1. 데이터 가져오기
            img_tensor, label_idx = dataset[i] # (image, label)
            path = dataset.samples[i][0]       # 파일 경로 (ImageFolder 기준)

            # 2. 모델 예측
            img_input = img_tensor.unsqueeze(0).to(device) # 배치 차원 추가
            outputs = model(img_input)
            _, pred_idx = torch.max(outputs, 1)

            true_label = class_names[label_idx]
            pred_label = class_names[pred_idx.item()]

            # 3. 타겟 조건 확인 (예: Buildings인데 Street로 예측한 것만)
            if target_pair:
                target_true, target_pred = target_pair
                if true_label != target_true or pred_label != target_pred:
                    continue
            else:
                # 타겟 없으면 그냥 맞춘건 패스
                if true_label == pred_label:
                    continue

            # 4. 결과 출력
            print(f"[검출] 실제: {true_label} | 예측: {pred_label} | 파일경로: {path}")
            count += 1

            if count >= 20: # 너무 많이 뜨면 보기 힘드니까 20개만 보고 멈춤 (조절 가능)
                print("... (너무 많아서 생략) ...")
                break

    print(f"-------- 검사 종료 (총 {count}건 발견) --------\n")

# ================= 실행 =================
# valid 데이터셋 원본을 가져옵니다 (Loader 말고 Dataset)
val_dataset = image_datasets['valid']

# 1. Buildings(실제) -> Street(오해) 파일명 찾기
find_misclassified_filenames(model, val_dataset, class_names, target_pair=('buildings', 'street'))

# 2. Street(실제) -> Buildings(오해) 파일명 찾기
find_misclassified_filenames(model, val_dataset, class_names, target_pair=('street', 'buildings'))

# 3. Culture(실제) -> Parks(오해) 파일명 찾기
find_misclassified_filenames(model, val_dataset, class_names, target_pair=('culture', 'parks'))

# 4. Parks(실제) -> Culture(오해) 파일명 찾기
find_misclassified_filenames(model, val_dataset, class_names, target_pair=('parks', 'culture'))

import os
import shutil

# ==========================================
# 1. 설정 (경로 확인)
# ==========================================
base_dir = '/content/valid'  # 사용자 경로

# ==========================================
# 2. 작업 리스트 작성
# ==========================================

# A. 이동할 파일들: ('파일명.jpg', '현재폴더', '이동할폴더')
# 예시: 'street_001.jpg'는 사실 건물이므로 buildings로 이동
files_to_move = [
    # ('파일명.jpg', '현재폴더', '새폴더')
    # buildings -> street
    ('11569.jpg', 'buildings', 'street'),
    ('13511.jpg', 'buildings', 'street'),
    ('20805.jpg', 'buildings', 'street'),
    ('20826.jpg', 'buildings', 'street'),
    ('20846.jpg', 'buildings', 'street'),
    ('23652.jpg', 'buildings', 'street'),
    ('23733.jpg', 'buildings', 'street'),
    ('4551.jpg', 'buildings', 'street'),
    ('7258.jpg', 'buildings', 'street'),
    ('7379.jpg', 'buildings', 'street'),
    # street -> buildings
    ('15584.jpg', 'street', 'buildings'),
    ('4556.jpg', 'street', 'buildings'),
    # culture -> parks
    ('e00351101002p0016.jpg', 'culture', 'parks'),
    ('f00289301002p0012.jpg', 'culture', 'parks'),
    ('g00040402002p0018.jpg', 'culture', 'parks'),
    ('g00107601006p0011.jpg', 'culture', 'parks'),
    # parks -> culture
    ('115.jpg', 'parks', 'culture'),
]

# B. 삭제할 파일들: ('파일명.jpg', '현재폴더')
# 예시: 'parks_999.jpg'는 너무 애매해서 삭제
files_to_delete = [
    # buildings -> street
    ('230.jpg', 'buildings'),
    ('4332.jpg', 'buildings'),
    ('4600.jpg', 'buildings'),
    ('6014.jpg', 'buildings'),
    ('8577.jpg', 'buildings'),
    # street -> buildings
    ('10732.jpg', 'street'),
    ('159.jpg', 'street'),
    # parks -> culture
    ('267.jpg', 'parks'),
]

# ==========================================
# 3. 실행 코드
# ==========================================

def process_files():
    print(f"작업 경로: {base_dir}\n")

    # 1. 파일 이동 처리
    print(f"--- [이동 작업] 총 {len(files_to_move)}건 ---")
    move_count = 0
    for filename, src_folder, dst_folder in files_to_move:
        src_path = os.path.join(base_dir, src_folder, filename)
        dst_path = os.path.join(base_dir, dst_folder, filename)

        if os.path.exists(src_path):
            try:
                shutil.move(src_path, dst_path)
                print(f"이동 완료: {src_folder}/{filename} -> {dst_folder}/")
                move_count += 1
            except Exception as e:
                print(f"이동 실패 ({filename}): {e}")
        else:
            print(f"파일 없음 (이미 이동/삭제됨): {src_folder}/{filename}")

    # 2. 파일 삭제 처리
    print(f"\n--- [삭제 작업] 총 {len(files_to_delete)}건 ---")
    del_count = 0
    for filename, folder in files_to_delete:
        file_path = os.path.join(base_dir, folder, filename)

        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                print(f"삭제 완료: {folder}/{filename}")
                del_count += 1
            except Exception as e:
                print(f"삭제 실패 ({filename}): {e}")
        else:
            print(f"파일 없음: {folder}/{filename}")

    print(f"\n 모든 작업 종료! (이동: {move_count}건, 삭제: {del_count}건)")

# 실행
process_files()

"""    2) test
    
"""

test_errors = visualize_specific_errors(
    model,
    dataloaders['test'],
    class_names,
    target_pairs_list
)

# 3. 시각화 출력
plot_errors_simple(test_errors)

test_dataset = image_datasets['test']

# 1. Buildings(실제) -> Street(오해) 파일명 찾기
find_misclassified_filenames(model, test_dataset, class_names, target_pair=('buildings', 'street'))

# 2. Street(실제) -> Buildings(오해) 파일명 찾기
find_misclassified_filenames(model, test_dataset, class_names, target_pair=('street', 'buildings'))

# 3. Culture(실제) -> Parks(오해) 파일명 찾기
find_misclassified_filenames(model, test_dataset, class_names, target_pair=('culture', 'parks'))

# 4. Parks(실제) -> Culture(오해) 파일명 찾기
find_misclassified_filenames(model, test_dataset, class_names, target_pair=('parks', 'culture'))

import os
import shutil

# ==========================================
# 1. 설정 (경로 확인)
# ==========================================
base_dir = '/content/test'  # 사용자 경로

# ==========================================
# 2. 작업 리스트 작성
# ==========================================

# A. 이동할 파일들: ('파일명.jpg', '현재폴더', '이동할폴더')
# 예시: 'street_001.jpg'는 사실 건물이므로 buildings로 이동
files_to_move = [
    # ('파일명.jpg', '현재폴더', '새폴더')
    # buildings -> street
    ('10056.jpg', 'buildings', 'street'),
    ('1311.jpg', 'buildings', 'street'),
    ('1643.jpg', 'buildings', 'street'),
    ('1739.jpg', 'buildings', 'street'),
    ('20764.jpg', 'buildings', 'street'),
    ('22596.jpg', 'buildings', 'street'),
    ('7241.jpg', 'buildings', 'street'),
    ('739.jpg', 'buildings', 'street'),
    ('8622.jpg', 'buildings', 'street'),
    # street -> buildings
    ('1838.jpg', 'street', 'buildings'),
    ('21694.jpg', 'street', 'buildings'),
    ('22233.jpg', 'street', 'buildings'),
    # culture -> parks
    ('e00120701003p0018.jpg', 'culture', 'parks'),
    ('e00130003004p0002.jpg', 'culture', 'parks'),
    ('e00258901003p0010.jpg', 'culture', 'parks'),
    ('e00293002002p0009.jpg', 'culture', 'parks'),
    ('g00051901004p0014.jpg', 'culture', 'parks'),
    ('g00065303002p0011.jpg', 'culture', 'parks'),
    ('h00020901003p0005.jpg', 'culture', 'parks'),
]

# B. 삭제할 파일들: ('파일명.jpg', '현재폴더')
# 예시: 'parks_999.jpg'는 너무 애매해서 삭제
files_to_delete = [
    # buildings -> street
    ('12703.jpg', 'buildings'),
    ('1629.jpg', 'buildings'),
    ('2043.jpg', 'buildings'),
    ('9498.jpg', 'buildings'),
    # street -> buildings
    ('10125.jpg', 'street'),
    ('10472.jpg', 'street'),
    ('8706.jpg', 'street'),
]

# ==========================================
# 3. 실행 코드 (수정하지 마세요)
# ==========================================

def process_files():
    print(f"작업 경로: {base_dir}\n")

    # 1. 파일 이동 처리
    print(f"--- [이동 작업] 총 {len(files_to_move)}건 ---")
    move_count = 0
    for filename, src_folder, dst_folder in files_to_move:
        src_path = os.path.join(base_dir, src_folder, filename)
        dst_path = os.path.join(base_dir, dst_folder, filename)

        if os.path.exists(src_path):
            try:
                shutil.move(src_path, dst_path)
                print(f"이동 완료: {src_folder}/{filename} -> {dst_folder}/")
                move_count += 1
            except Exception as e:
                print(f"이동 실패 ({filename}): {e}")
        else:
            print(f"파일 없음 (이미 이동/삭제됨): {src_folder}/{filename}")

    # 2. 파일 삭제 처리
    print(f"\n--- [삭제 작업] 총 {len(files_to_delete)}건 ---")
    del_count = 0
    for filename, folder in files_to_delete:
        file_path = os.path.join(base_dir, folder, filename)

        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                print(f"삭제 완료: {folder}/{filename}")
                del_count += 1
            except Exception as e:
                print(f"삭제 실패 ({filename}): {e}")
        else:
            print(f"파일 없음: {folder}/{filename}")

    print(f"\n 모든 작업 종료! (이동: {move_count}건, 삭제: {del_count}건)")

# 실행
process_files()

"""이미 학습된 모델로 train 데이터 검토 (**Human-in-the-loop**)"""

import torch
import os
import matplotlib.pyplot as plt
import numpy as np
import math

def inspect_train_errors(model, train_dataset, class_names, target_pairs):
    """
    Train 데이터셋에서 '모델 예측'과 '실제 라벨'이 다른 경우만 찾아내는 함수
    (양이 많으므로 target_pairs에 해당하는 것만 집중적으로 봅니다)
    """
    print(f"Train 데이터 검수 시작... (타겟: {target_pairs})")

    # 중요: Train은 원래 섞여(Shuffle) 있지만, 파일명 매칭을 위해
    # 순서대로(Shuffle=False) 불러오는 임시 로더를 만듭니다.
    temp_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=32,
        shuffle=False,  # <--- 이게 핵심! 순서대로 읽어야 파일명이 맞음
        num_workers=8,
        pin_memory=True
        )

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    suspicious_samples = []
    current_idx = 0

    with torch.no_grad():
        for inputs, labels in temp_loader:
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            # 틀린 것 찾기
            not_matches = (preds != labels)
            error_indices = np.where(not_matches.cpu().numpy())[0]

            for local_idx in error_indices:
                global_idx = current_idx + local_idx

                true_idx = labels[local_idx].item()
                pred_idx = preds[local_idx].item()

                true_label = class_names[true_idx]
                pred_label = class_names[pred_idx]

                # 우리가 관심 있는 혼동 패턴인지 확인
                if (true_label, pred_label) in target_pairs:

                    # 파일 경로 가져오기
                    full_path = train_dataset.samples[global_idx][0]
                    filename = os.path.basename(full_path)

                    suspicious_samples.append({
                        'img_tensor': inputs[local_idx].cpu(),
                        'true': true_label,
                        'pred': pred_label,
                        'filename': filename
                    })

            current_idx += inputs.size(0)

            # (옵션) 너무 많이 나오면 50개만 보고 멈추기
            # if len(suspicious_samples) > 50: break

    print(f"의심스러운 Train 데이터 {len(suspicious_samples)}장 발견!")
    return suspicious_samples

# ================= 실행 =================

# 1. 타겟 정의 (가장 문제였던 4가지)
target_pairs_list = [
    ('buildings', 'street'),
    ('street', 'buildings'),
    ('parks', 'culture'),
    ('culture', 'parks')
]

# 2. Train 데이터셋 원본 가져오기
train_dataset = image_datasets['train']

# 3. 검사 실행
suspicious_train_data = inspect_train_errors(
    model,
    train_dataset,
    class_names,
    target_pairs_list
)

# 4. 시각화 (방금 썼던 그 함수 그대로 사용)
# 만약 이미지가 너무 많으면 위 코드의 break 주석을 풀어서 조금씩 보세요.
plot_errors_simple(suspicious_train_data)

import torch
import os
from torch.utils.data import DataLoader

def find_suspicious_train_filenames(model, dataset, class_names, target_pairs):
    """
    Train 데이터셋을 빠르게 훑으면서 '모델이 헷갈려하는' 파일명만 추출합니다.
    """
    print(f"Train 데이터 정밀 검사 시작... (감시 대상: {len(target_pairs)}종)")

    # Shuffle=False로 설정하여 순서대로 로딩
    temp_loader = DataLoader(dataset, batch_size=64, shuffle=False, num_workers=8, pin_memory=True)

    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    count = 0
    current_idx = 0

    with torch.no_grad():
        for inputs, labels in temp_loader:
            inputs = inputs.to(device)
            labels = labels.to(device)

            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            # 틀린 것 마스킹
            not_matches = (preds != labels)
            error_indices = torch.where(not_matches)[0].cpu().numpy()

            for local_idx in error_indices:
                true_idx = labels[local_idx].item()
                pred_idx = preds[local_idx].item()

                true_label = class_names[true_idx]
                pred_label = class_names[pred_idx]

                # 우리가 찾는 타겟인지 확인
                if (true_label, pred_label) in target_pairs:

                    global_idx = current_idx + local_idx
                    full_path = dataset.samples[global_idx][0]

                    # [수정된 부분] 경로에서 파일명만 쏙 빼내기
                    filename = os.path.basename(full_path)

                    # 출력 형식 변경 (경로 -> 파일명)
                    print(f"[의심] 실제: {true_label} <-> 예측: {pred_label} | 파일명: {filename}")
                    count += 1

            current_idx += inputs.size(0)

    print(f"\n-------- 검사 종료 (총 {count}개의 의심 파일 발견) --------")

# ================= 실행 =================
target_pairs_list = [
    ('buildings', 'street'),
    ('street', 'buildings'),
    ('parks', 'culture'),
    ('culture', 'parks')
]

train_dataset = image_datasets['train']

find_suspicious_train_filenames(
    model,
    train_dataset,
    class_names,
    target_pairs_list
)

import os
import shutil

# ==========================================
# 1. 설정 (경로 확인)
# ==========================================
base_dir = '/content/train'  # 사용자 경로

# ==========================================
# 2. 작업 리스트 작성
# ==========================================

# A. 이동할 파일들: ('파일명.jpg', '현재폴더', '이동할폴더')
# 예시: 'street_001.jpg'는 사실 건물이므로 buildings로 이동
files_to_move = [
    # ('파일명.jpg', '현재폴더', '새폴더')
    # buildings -> street
    ('10511.jpg', 'buildings', 'street'),
    ('10878.jpg', 'buildings', 'street'),
    ('10899.jpg', 'buildings', 'street'),
    ('11302.jpg', 'buildings', 'street'),
    ('12517.jpg', 'buildings', 'street'),
    ('13590.jpg', 'buildings', 'street'),
    ('13746.jpg', 'buildings', 'street'),
    ('13969.jpg', 'buildings', 'street'),
    ('14535.jpg', 'buildings', 'street'),
    ('1471.jpg', 'buildings', 'street'),
    ('15320.jpg', 'buildings', 'street'),
    ('1587.jpg', 'buildings', 'street'),
    ('16279.jpg', 'buildings', 'street'),
    ('16793.jpg', 'buildings', 'street'),
    ('16933.jpg', 'buildings', 'street'),
    ('17581.jpg', 'buildings', 'street'),
    ('18235.jpg', 'buildings', 'street'),
    ('1879.jpg', 'buildings', 'street'),
    ('19089.jpg', 'buildings', 'street'),
    ('19830.jpg', 'buildings', 'street'),
    ('21506.jpg', 'buildings', 'street'),
    ('22031.jpg', 'buildings', 'street'),
    ('22266.jpg', 'buildings', 'street'),
    ('23727.jpg', 'buildings', 'street'),
    ('24290.jpg', 'buildings', 'street'),
    ('3540.jpg', 'buildings', 'street'),
    ('3638.jpg', 'buildings', 'street'),
    ('4000.jpg', 'buildings', 'street'),
    ('4152.jpg', 'buildings', 'street'),
    ('5152.jpg', 'buildings', 'street'),
    ('7214.jpg', 'buildings', 'street'),
    ('8748.jpg', 'buildings', 'street'),
    ('9699.jpg', 'buildings', 'street'),
    ('9921.jpg', 'buildings', 'street'),
    # street -> buildings
    ('10514.jpg', 'street', 'buildings'),
    ('11812.jpg', 'street', 'buildings'),
    ('1194.jpg', 'street', 'buildings'),
    ('11944.jpg', 'street', 'buildings'),
    ('14399.jpg', 'street', 'buildings'),
    ('15599.jpg', 'street', 'buildings'),
    ('15961.jpg', 'street', 'buildings'),
    ('16189.jpg', 'street', 'buildings'),
    ('16258.jpg', 'street', 'buildings'),
    ('16693.jpg', 'street', 'buildings'),
    ('17887.jpg', 'street', 'buildings'),
    ('18466.jpg', 'street', 'buildings'),
    ('18905.jpg', 'street', 'buildings'),
    ('20286.jpg', 'street', 'buildings'),
    ('22351.jpg', 'street', 'buildings'),
    ('24280.jpg', 'street', 'buildings'),
    ('3109.jpg', 'street', 'buildings'),
    ('3412.jpg', 'street', 'buildings'),
    ('3440.jpg', 'street', 'buildings'),
    ('3461.jpg', 'street', 'buildings'),
    ('3764.jpg', 'street', 'buildings'),
    ('4963.jpg', 'street', 'buildings'),
    ('6392.jpg', 'street', 'buildings'),
    ('6786.jpg', 'street', 'buildings'),
    ('7293.jpg', 'street', 'buildings'),
    ('7888.jpg', 'street', 'buildings'),
    ('9009.jpg', 'street', 'buildings'),
    ('9108.jpg', 'street', 'buildings'),
    ('9169.jpg', 'street', 'buildings'),
    ('9299.jpg', 'street', 'buildings'),
    # culture -> parks
    ('e00048301002p0006.jpg', 'culture', 'parks'),
    ('e00049001006p0003.jpg', 'culture', 'parks'),
    ('e00096901002p0004.jpg', 'culture', 'parks'),
    ('e00207001007p0003.jpg', 'culture', 'parks'),
    ('e00215401005p0004.jpg', 'culture', 'parks'),
    ('e00218401003p0011.jpg', 'culture', 'parks'),
    ('e00219801005p0009.jpg', 'culture', 'parks'),
    ('e00233201003p0019.jpg', 'culture', 'parks'),
    ('e00247701003p0019.jpg', 'culture', 'parks'),
    ('e00258302006p0001.jpg', 'culture', 'parks'),
    ('e00311802004p0005.jpg', 'culture', 'parks'),
    ('e00467802002p0001.jpg', 'culture', 'parks'),
    ('e00471602002p0004.jpg', 'culture', 'parks'),
    ('e00540702003p0003.jpg', 'culture', 'parks'),
    ('e00540702003p0014.jpg', 'culture', 'parks'),
    ('f00028002003p0005.jpg', 'culture', 'parks'),
    ('f00057502003p0003.jpg', 'culture', 'parks'),
    ('f00061001005p0006.jpg', 'culture', 'parks'),
    ('f00085901007p0005.jpg', 'culture', 'parks'),
    ('f00173201003p0005.jpg', 'culture', 'parks'),
    ('f00175901002p0001.jpg', 'culture', 'parks'),
    ('f00211401004p0004.jpg', 'culture', 'parks'),
    ('f00212302003p0003.jpg', 'culture', 'parks'),
    ('f00262001005p0001.jpg', 'culture', 'parks'),
    ('f00325601003p0008.jpg', 'culture', 'parks'),
    ('f00334101002p0001.jpg', 'culture', 'parks'),
    ('g00029001004p0001.jpg', 'culture', 'parks'),
    ('g00047104002p0004.jpg', 'culture', 'parks'),
    ('g00056202004p0008.jpg', 'culture', 'parks'),
    ('g00107601006p0008.jpg', 'culture', 'parks'),
    ('g00120901005p0001.jpg', 'culture', 'parks'),
    ('g00165101006p0006.jpg', 'culture', 'parks'),
    ('g00191601003p0002.jpg', 'culture', 'parks'),
    ('g00253701010p0003.jpg', 'culture', 'parks'),
    ('g00256601005p0006.jpg', 'culture', 'parks'),
    ('g00272401002p0009.jpg', 'culture', 'parks'),
    ('g00301001002p0009.jpg', 'culture', 'parks'),
    ('g00384601003p0009.jpg', 'culture', 'parks'),
    ('h00226502008p0004.jpg', 'culture', 'parks'),
    # parks -> culture
    ('109.jpg', 'parks', 'culture'),
    ('367.jpg', 'parks', 'culture'),
]

# B. 삭제할 파일들: ('파일명.jpg', '현재폴더')
# 예시: 'parks_999.jpg'는 너무 애매해서 삭제
files_to_delete = [
    # buildings
    ('10367.jpg', 'buildings'),
    ('10656.jpg', 'buildings'),
    ('10699.jpg', 'buildings'),
    ('1104.jpg', 'buildings'),
    ('11627.jpg', 'buildings'),
    ('11628.jpg', 'buildings'),
    ('11827.jpg', 'buildings'),
    ('12169.jpg', 'buildings'),
    ('12934.jpg', 'buildings'),
    ('13220.jpg', 'buildings'),
    ('14001.jpg', 'buildings'),
    ('14294.jpg', 'buildings'),
    ('14984.jpg', 'buildings'),
    ('15109.jpg', 'buildings'),
    ('15293.jpg', 'buildings'),
    ('17545.jpg', 'buildings'),
    ('19101.jpg', 'buildings'),
    ('20425.jpg', 'buildings'),
    ('20550.jpg', 'buildings'),
    ('21772.jpg', 'buildings'),
    ('2430.jpg', 'buildings'),
    ('2602.jpg', 'buildings'),
    ('2880.jpg', 'buildings'),
    ('292.jpg', 'buildings'),
    ('367.jpg', 'buildings'),
    ('3829.jpg', 'buildings'),
    ('3869.jpg', 'buildings'),
    ('4631.jpg', 'buildings'),
    ('7282.jpg', 'buildings'),
    ('9019.jpg', 'buildings'),
    # street
    ('11143.jpg', 'street'),
    ('13035.jpg', 'street'),
    ('13605.jpg', 'street'),
    ('14037.jpg', 'street'),
    ('14168.jpg', 'street'),
    ('14479.jpg', 'street'),
    ('14910.jpg', 'street'),
    ('15072.jpg', 'street'),
    ('15115.jpg', 'street'),
    ('15644.jpg', 'street'),
    ('16320.jpg', 'street'),
    ('16695.jpg', 'street'),
    ('17852.jpg', 'street'),
    ('2068.jpg', 'street'),
    ('21077.jpg', 'street'),
    ('21653.jpg', 'street'),
    # parks
    ('0137.jpg', 'parks'),
    ('0148.jpg', 'parks'),
]

# ==========================================
# 3. 실행 코드
# ==========================================

def process_files():
    print(f"작업 경로: {base_dir}\n")

    # 1. 파일 이동 처리
    print(f"--- [이동 작업] 총 {len(files_to_move)}건 ---")
    move_count = 0
    for filename, src_folder, dst_folder in files_to_move:
        src_path = os.path.join(base_dir, src_folder, filename)
        dst_path = os.path.join(base_dir, dst_folder, filename)

        if os.path.exists(src_path):
            try:
                shutil.move(src_path, dst_path)
                print(f"이동 완료: {src_folder}/{filename} -> {dst_folder}/")
                move_count += 1
            except Exception as e:
                print(f"이동 실패 ({filename}): {e}")
        else:
            print(f"파일 없음 (이미 이동/삭제됨): {src_folder}/{filename}")

    # 2. 파일 삭제 처리
    print(f"\n--- [삭제 작업] 총 {len(files_to_delete)}건 ---")
    del_count = 0
    for filename, folder in files_to_delete:
        file_path = os.path.join(base_dir, folder, filename)

        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                print(f"삭제 완료: {folder}/{filename}")
                del_count += 1
            except Exception as e:
                print(f"삭제 실패 ({filename}): {e}")
        else:
            print(f"파일 없음: {folder}/{filename}")

    print(f"\n 모든 작업 종료! (이동: {move_count}건, 삭제: {del_count}건)")

# 실행
process_files()

"""[2단계] 데이터 정제(Data Refinement)"""

set_seed(42)

# ==========================================
# [중요] 데이터셋 새로고침 (청소된 데이터 반영)
# ==========================================
# 데이터가 이동/삭제되었으므로 image_datasets를 다시 읽어야함.
image_datasets = {
    x: datasets.ImageFolder(os.path.join(DATA_PATH, x), transform_config)
    for x in ['train', 'valid', 'test']
}
dataloaders = {
    x: DataLoader(image_datasets[x], batch_size=BATCH_SIZE, shuffle=(x == 'train'), num_workers=8, pin_memory=True)
    for x in ['train', 'valid', 'test']
}
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'valid', 'test']}
print(f"데이터셋 새로고침 완료! (Train 개수: {dataset_sizes['train']})")


# ==========================================
# [2차 학습]
# ==========================================
print("\n--- 전이학습(재학습) 시작 ---")
# [중요] 이미 학습된 모델이므로 학습률을 낮게 잡습니다 (Fine-tuning)
# 기존에 0.001을 썼다면, 이번엔 0.0001(1e-4) 정도 추천
optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

EPOCHS = 10

best_model_wts2 = copy.deepcopy(model.state_dict())
best_acc2 = 0.0

start_time = time.time()

for epoch in range(EPOCHS):
    for phase in ['train', 'valid']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_loss = 0.0
        running_corrects = 0

        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            # 통계 계산
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / len(image_datasets[phase])

        # 정확도 출력
        print(f"[{phase}] Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}")

        # 검증일 때만 최고 모델 저장
        if phase == 'valid' and epoch_acc > best_acc2:
            best_acc2 = epoch_acc
            best_model_wts2 = copy.deepcopy(model.state_dict())

time_elapsed = time.time() - start_time
print(f'\n학습 완료! 소요 시간: {time_elapsed // 60:.0f}분 {time_elapsed % 60:.0f}초')
print(f"최고 검증 정확도: {best_acc2:.4f}")

print(f"재학습 완료! 최고 검증 정확도: {best_acc2:.4f}")

# 1차 학습(best_acc)과 2차 학습(best_acc2) 비교
if 'best_acc' in globals():
    diff = best_acc2 - best_acc
    print(f"성능 변화: {best_acc:.4f} -> {best_acc2:.4f} ({diff:+.4f})")

# 최고 성능 모델 로드
model.load_state_dict(best_model_wts2)

# [재학습 후] 최종 Test 데이터 평가
print("--- [재학습 후] 최종 Test 데이터 평가 시작 ---")

model.eval() # 평가 모드 (필수)
correct = 0
total = 0

with torch.no_grad(): # 기울기 계산 끔 (메모리 절약)
    for inputs, labels in dataloaders['test']:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_acc2 = 100 * correct / total
print(f"재학습 후 최종 Test 정확도: {test_acc2:.2f}%")

# 1차 학습 결과와 비교
if 'test_acc' in globals():
    diff = test_acc2 - test_acc
    print(f"성능 변화: {test_acc:.2f}% -> {test_acc2:.2f}% ({diff:+.2f}%p)")

    if diff > 0:
        print("데이터 청소 효과로 성능이 향상됨.")
    elif diff == 0:
        print("성능 변화가 없음.")
    else:
        print("성능이 떨어짐.")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

def plot_final_confusion_matrix(model, dataloader, class_names):
    model.eval()
    all_preds = []
    all_labels = []

    print("최종 Confusion Matrix 생성 중...")

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # 혼동 행렬 계산
    cm = confusion_matrix(all_labels, all_preds)

    # 시각화
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label (Actual)')
    plt.title('Confusion Matrix v2 (After Cleaning)')
    plt.show()

# 실행
plot_final_confusion_matrix(model, dataloaders['test'], class_names)

from sklearn.metrics import classification_report

def get_detailed_report(model, dataloader):
    y_true = []
    y_pred = []

    model.eval()
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 정밀도, 재현율, F1-score 출력
    print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

print("--- 클래스별 상세 성적표 (F1-Score) ---")
get_detailed_report(model, dataloaders['test'])

"""[3단계] 미세 조정(Fine-tuning)"""

print(model)

import torch
import torch.nn as nn
import torch.optim as optim

# ==========================================
# 1. [필수] Random Seed 고정 (재현성 확보)
# ==========================================
set_seed(42)

# ==========================================
# 2. 레이어 선별적 해제 (Smart Unfreezing)
# ==========================================
# (1) 일단 모든 파라미터 얼리기 (Freeze)
for param in model.parameters():
    param.requires_grad = False

# (2) Classifier(분류기)는 무조건 학습 (잠금 해제)
for param in model.classifier.parameters():
    param.requires_grad = True

# (3) [핵심] EfficientNet의 '눈'인 Feature Extractor(Backbone)의 뒷부분만 '선별적'으로 잠금 해제
# features.7 : 최종 특징을 1280개 채널로 확장하는 중요한 다리 역할
for param in model.features[7].parameters():
    param.requires_grad = True

# features.6 : 가장 고차원적인 패턴(건물 창문 vs 도로 질감)을 담당
# features.6은 총 15개(0~14) 블록이 있는데, 뒤쪽 5개(10~14)만 풀어줍니다.
# 너무 많이 풀면 과적합 위험이 있으니 딱 이 정도가 적당합니다.
for i in range(10, 15):
    for param in model.features[6][i].parameters():
        param.requires_grad = True

# ==========================================
# 3. 차등 학습률 (Differential Learning Rate)
# ==========================================
# 층마다 학습률을 다르게 주는 고급 기법
optimizer = optim.AdamW([
    {
        # 가장 깊은 곳 (Features 6): 기존 지식을 까먹지 않게 아주 살살 학습
        'params': [p for i in range(10, 15) for p in model.features[6][i].parameters()],
        'lr': 1e-5
    },
    {
        # 연결 다리 (Features 7): 중간 강도로 학습
        'params': model.features[7].parameters(),
        'lr': 2e-5
    },
    {
        # 분류기 (Classifier): 내 데이터에 맞춰야 하니 가장 세게 학습
        'params': model.classifier.parameters(),
        'lr': 1e-3
    }
], weight_decay=1e-4)

# 4. 스케줄러 & 손실함수
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20, eta_min=1e-6)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1) # 헷갈리는 클래스 완화

print("모델 튜닝 준비 완료: Features.6(후반부) + Features.7 + Classifier 잠금 해제됨")

import time
import copy

num_epochs = 20

# 변수명 변경 (v3)
best_acc3 = 0.0
best_model_wts3 = copy.deepcopy(model.state_dict())

# 결과 기록용 (v3)
history3 = {'train_loss': [], 'train_acc': [], 'valid_loss': [], 'valid_acc': []}

print(f"--- 튜닝 시작 (Target: Buildings vs Street) [Ver.3] ---")
start_time = time.time()

for epoch in range(num_epochs):
    print(f'Epoch {epoch+1}/{num_epochs}')

    # 각 에폭(Epoch)은 학습(train)과 검증(val) 단계로 나뉨
    for phase in ['train', 'valid']:
        if phase == 'train':
            model.train()  # 모델을 학습 모드로 설정
        else:
            model.eval()   # 모델을 평가 모드로 설정

        running_loss = 0.0
        running_corrects = 0

        # 데이터 반복 (Batch)
        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            # 매개변수 경사도 초기화
            optimizer.zero_grad()

            # 순전파 (Forward)
            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                # 역전파 (Backward) + 최적화 (Optimize) - 학습 단계에서만
                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            # 통계 계산
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        # 학습 단계가 끝나면 스케줄러 업데이트 (CosineAnnealing)
        if phase == 'train':
            scheduler.step()
            # 현재 학습률 출력 (제대로 줄어들고 있는지 확인용)
            current_lr = optimizer.param_groups[0]['lr']
            # print(f"Current LR: {current_lr:.8f}") # 너무 시끄러우면 주석 처리

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        history3[f'{phase}_loss'].append(epoch_loss)
        history3[f'{phase}_acc'].append(epoch_acc.item())

        print(f'{phase} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

        # 모델을 깊게 복사(Deep Copy)하여 최고 성능 모델 저장 (v3)
        if phase == 'valid' and epoch_acc > best_acc3:
            best_acc3 = epoch_acc
            best_model_wts3 = copy.deepcopy(model.state_dict())

            # 파일명도 v3로 저장
            torch.save(model.state_dict(), 'best_finetuned_model_v3.pth')
            print(f"--> 최고 성능 갱신! 저장됨 (Acc: {best_acc3:.4f})")

    print()

time_elapsed = time.time() - start_time
print(f'학습 완료: {time_elapsed // 60:.0f}분 {time_elapsed % 60:.0f}초 소요')
print(f'최고 Val 정확도 (v3): {best_acc3:.4f}')

# 최고 성능 가중치로 모델 로드
model.load_state_dict(best_model_wts3)

import matplotlib.pyplot as plt
import numpy as np

def plot_history_v3(history):
    # 1. 데이터 추출
    acc = history['train_acc']
    val_acc = history['valid_acc']
    loss = history['train_loss']
    val_loss = history['valid_loss']

    epochs_range = range(1, len(acc) + 1)

    # 2. 최고 성능 시점 찾기 (Validation Accuracy 기준)
    best_epoch = np.argmax(val_acc) + 1 # 인덱스는 0부터 시작하므로 +1
    best_val_acc = max(val_acc)

    # 3. 그래프 스타일 설정 (가독성 UP)
    plt.style.use('seaborn-v0_8-whitegrid')
    plt.figure(figsize=(10, 4))

    # --- 정확도(Accuracy) 그래프 ---
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy', color='royalblue', linewidth=2)
    plt.plot(epochs_range, val_acc, label='Validation Accuracy', color='tomato', linewidth=2, marker='o')

    # 최고점 표시 (별표)
    plt.scatter(best_epoch, best_val_acc, color='red', s=200, marker='*', zorder=5, label=f'Best Epoch: {best_epoch}')
    plt.annotate(f'{best_val_acc:.4f}', (best_epoch, best_val_acc), xytext=(0, 10), textcoords='offset points', ha='center', fontsize=12, fontweight='bold')

    plt.title('Accuracy Progress (Fine-tuning)', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend(loc='lower right')

    # --- 손실(Loss) 그래프 ---
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, label='Training Loss', color='royalblue', linewidth=2)
    plt.plot(epochs_range, val_loss, label='Validation Loss', color='tomato', linewidth=2, marker='o')
    plt.title('Loss Progress (Fine-tuning)', fontsize=14)
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend(loc='upper right')

    plt.tight_layout()

# 실행
plot_history_v3(history3)

# 1. 모델 초기화 및 가중치 로드
# (방금 학습해서 저장한 v3 파일 로드)
weights_path = 'best_finetuned_model_v3.pth'
model.load_state_dict(torch.load(weights_path))
model.to(device)

# 2. 평가 모드 설정
model.eval()
criterion = torch.nn.CrossEntropyLoss() # Loss 계산용

correct = 0
total = 0
running_loss = 0.0 # Loss 누적을 위한 변수 추가

with torch.no_grad(): # 기울기 계산 끔 (메모리 절약 & 속도 향상)
    for inputs, labels in dataloaders['test']:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        loss = criterion(outputs, labels) # 배치의 Loss 계산

        total += labels.size(0)
        correct += (predicted == labels).sum().item()
        running_loss += loss.item() * inputs.size(0) # 전체 Loss 합산

# 최종 결과 계산
final_loss = running_loss / total
test_acc3 = 100 * correct / total

# ==========================================
# 성능 비교 (Step 1 vs Step 2 vs Step 3)
# ==========================================
print("\n--- 단계별 성능 비교 ---")

# 1. Baseline(1차)과 비교
if 'test_acc' in globals():
    diff1 = test_acc3 - test_acc
    print(f"Step 1 (Baseline) 대비: {test_acc:.2f}% -> {test_acc3:.2f}% ({diff1:+.2f}%p)")

# 2. Cleaning(2차)과 비교
if 'test_acc2' in globals():
    diff2 = test_acc3 - test_acc2
    print(f"Step 2 (Cleaning) 대비: {test_acc2:.2f}% -> {test_acc3:.2f}% ({diff2:+.2f}%p)")

    if diff2 > 0:
        print("Fine-tuning 효과로 성능이 추가 향상되었습니다!")
    elif diff2 == 0:
        print("성능 변화가 없습니다.")
    else:
        print("성능이 다소 떨어졌습니다. (과적합 가능성 체크 필요)")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

def plot_final_confusion_matrix(model, dataloader, class_names):
    model.eval()
    all_preds = []
    all_labels = []

    print("최종 Confusion Matrix 생성 중...")

    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # 혼동 행렬 계산
    cm = confusion_matrix(all_labels, all_preds)

    # 시각화
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label (Actual)')
    plt.title('Confusion Matrix v3 (After Fine-tuning)')
    plt.show()

# 실행
plot_final_confusion_matrix(model, dataloaders['test'], class_names)

from sklearn.metrics import classification_report

def get_detailed_report(model, dataloader):
    y_true = []
    y_pred = []

    model.eval()
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)

            y_true.extend(labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 정밀도, 재현율, F1-score 출력
    print(classification_report(y_true, y_pred, target_names=class_names, digits=4))

print("--- 클래스별 상세 성적표 (F1-Score) ---")
get_detailed_report(model, dataloaders['test'])

"""[4단계] 데이터 증강(Data Augmentation)"""

import os
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# ==========================================
# 0. Random Seed 고정 (필수)
# 증강(Augmentation)에도 랜덤성이 들어가므로 시드 고정이 매우 중요함
# ==========================================
set_seed(42)

# ==========================================
# 1. 경로 및 설정
# ==========================================
DATA_PATH = '/content'
BATCH_SIZE = 64
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================
# 2. [핵심] v4용 데이터 증강 설정 정의
# ==========================================
# train에는 '어렵게 만드는 변환'을, valid/test에는 '정석 변환'을 적용
data_transforms_v4 = {
    'train': transforms.Compose([
        # 1. RandomResizedCrop: 이미지를 랜덤한 크기(0.8~1.0)와 비율로 자름
        # -> 건물의 전체가 아닌 '일부분(창문, 간판 등)'만 보고도 맞추게 훈련됨 (학습 효과 극대화)
        transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),

        # 좌우 반전
        transforms.RandomHorizontalFlip(p=0.5),

        # 약간 회전 (-15도 ~ +15도)
        transforms.RandomRotation(degrees=15),

        # ColorJitter: 밝기, 대비, 채도 변화 (날씨나 조명 변화 대응)
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),

        # 텐서 변환 및 정규화 (필수)
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),

    # Valid/Test는 이미지 형태를 왜곡하지 않고 원본의 특징을 그대로 평가해야 함 (Resize -> CenterCrop)
    'valid': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),

    'test': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
}

# ==========================================
# 3. 데이터셋 & 로더 새로고침 (v4 적용)
# ==========================================
image_datasets = {
    x: datasets.ImageFolder(os.path.join(DATA_PATH, x), data_transforms_v4[x])
    for x in ['train', 'valid', 'test']
}

dataloaders = {
    x: DataLoader(image_datasets[x], batch_size=BATCH_SIZE, shuffle=(x == 'train'), num_workers=8, pin_memory=True)
    for x in ['train', 'valid', 'test']
}

# 데이터 개수 변수 업데이트
dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'valid', 'test']}
class_names = image_datasets['train'].classes

print("v4 데이터 로더 준비 완료!")
print(f"적용된 증강 기법: RandomResizedCrop, Flip, Rotation, ColorJitter")
print(f"데이터셋 크기: {dataset_sizes}")

# ==========================================
# 4. 클래스 가중치(Class Weights) 자동 계산
# ==========================================
print("\n--- 클래스별 가중치 계산 중 ---")

# Train 데이터셋의 타겟(라벨) 정보 가져오기
train_targets = image_datasets['train'].targets

# 클래스별 개수 세기
class_counts = np.bincount(train_targets)
total_samples = len(train_targets)
num_classes = len(class_names)

# 가중치 계산 공식: (전체 개수) / (클래스 수 * 해당 클래스 개수)
# 이렇게 하면 개수가 적은 클래스는 값이 커지고, 많은 클래스는 작아집니다.
class_weights = total_samples / (num_classes * class_counts)

# 텐서로 변환 및 GPU로 이동
class_weights_tensor = torch.FloatTensor(class_weights).to(device)

# 결과 출력 (검증용)
for i, name in enumerate(class_names):
    print(f"Class '{name}': {class_counts[i]}장 -> Weight: {class_weights[i]:.4f}")
    if name == 'parks': # 공원 가중치 확인
        print(f"--> [Check] 공원(parks)의 가중치가 다른 클래스보다 높아야 합니다.")

# ==========================================
# 5. 손실 함수에 가중치 적용
# ==========================================
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

print("\n손실 함수(Loss Function)에 가중치 적용 완료!")

import torch
import torch.nn as nn
import torch.optim as optim
import time
import copy

set_seed(42)

# ==========================================
# 1. 시작점 설정: Step 3 최고 모델 불러오기
# ==========================================
# 바닥부터 하지 않고, 98.55% 점수를 받은 모델에서 시작
weights_path = 'best_finetuned_model_v3.pth'
model.load_state_dict(torch.load(weights_path))
model.to(device)

print(f"Step 3 최고 성능 모델 로드 완료! (여기서부터 증강 학습 시작)")

# ==========================================
# 2. 레이어 선별적 해제 (Smart Unfreezing)
# ==========================================
# Step 3와 동일한 전략 수행
# (1) 일단 모든 파라미터 얼리기
for param in model.parameters():
    param.requires_grad = False

# (2) Classifier 무조건 학습
for param in model.classifier.parameters():
    param.requires_grad = True

# (3) Features[7] (다리 역할) 해제
for param in model.features[7].parameters():
    param.requires_grad = True

# (4) Features[6] (핵심 특징) 뒤쪽 5개만 해제
for i in range(10, 15):
    for param in model.features[6][i].parameters():
        param.requires_grad = True

# ==========================================
# 3. Optimizer & Scheduler (차등 학습률 + 가중치 적용)
# ==========================================
optimizer = optim.AdamW([
    {
        # 가장 깊은 곳 (Features 6): 아주 살살 학습
        'params': [p for i in range(10, 15) for p in model.features[6][i].parameters()],
        'lr': 1e-5
    },
    {
        # 연결 다리 (Features 7): 중간 강도
        'params': model.features[7].parameters(),
        'lr': 2e-5
    },
    {
        # 분류기 (Classifier): 강하게 학습
        'params': model.classifier.parameters(),
        'lr': 1e-3
    }
], weight_decay=1e-4)

# 스케줄러 & 손실함수
# weight: 클래스 불균형 해결 (공원 맞추면 점수 더 줌)
# label_smoothing: 과적합 방지 (정답을 1.0이 아니라 0.9 정도로 생각하게 함)
num_epochs = 20
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs, eta_min=1e-6)
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)

# ==========================================
# 4. 학습 루프 실행 (v4)
# ==========================================
best_acc4 = 0.0
best_model_wts4 = copy.deepcopy(model.state_dict())
history4 = {'train_loss': [], 'train_acc': [], 'valid_loss': [], 'valid_acc': []}

print(f"\n--- [Final Step] Augmentation(v4) 학습 시작 ---")
start_time = time.time()

for epoch in range(num_epochs):
    print(f'Epoch {epoch+1}/{num_epochs}')

    for phase in ['train', 'valid']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_loss = 0.0
        running_corrects = 0

        # 여기서 dataloaders는 아까 만든 v4용 로더여야 합니다!
        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        if phase == 'train':
            scheduler.step()

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        history4[f'{phase}_loss'].append(epoch_loss)
        history4[f'{phase}_acc'].append(epoch_acc.item())

        print(f'  [{phase}] Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

        # 최고 성능 갱신 시 저장 (v4 파일명)
        if phase == 'valid' and epoch_acc > best_acc4:
            best_acc4 = epoch_acc
            best_model_wts4 = copy.deepcopy(model.state_dict())
            torch.save(model.state_dict(), 'best_finetuned_model_v4.pth')
            print(f"  --> 최고 성능 갱신! (Acc: {best_acc4:.4f})")

time_elapsed = time.time() - start_time
print(f'\n최종 학습 완료: {time_elapsed // 60:.0f}분 {time_elapsed % 60:.0f}초 소요')
print(f'최고 Val 정확도 (v4): {best_acc4:.4f}')

# 모델 로드
model.load_state_dict(best_model_wts4)

# 1. 모델 초기화 및 가중치 로드
weights_path = 'best_finetuned_model_v4.pth'
model.load_state_dict(torch.load(weights_path))
model.to(device)

# 2. 평가 모드 설정
model.eval()
criterion = torch.nn.CrossEntropyLoss() # Loss 계산용

correct = 0
total = 0
running_loss = 0.0

print("--- [Step 4] Final Test (Augmentation 적용 모델) 평가 시작 ---")

with torch.no_grad():
    for inputs, labels in dataloaders['test']:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        loss = criterion(outputs, labels) # 배치의 Loss 계산

        total += labels.size(0)
        correct += (predicted == labels).sum().item()
        running_loss += loss.item() * inputs.size(0) # 전체 Loss 합산

# 최종 결과 계산
final_loss = running_loss / total
test_acc4 = 100 * correct / total

print(f"\n[최종 성적표 (Step 4)]")
print(f"Loss: {final_loss:.4f}")
print(f"Accuracy: {test_acc4:.2f}%")

# ================================================
# 단계별 성능 비교 (The Grand Finale)
# ================================================
print("\n--- 단계별 성능 변화 ---")

# 1. Baseline(1차)과 비교
if 'test_acc' in globals():
    diff1 = test_acc4 - test_acc
    print(f"Step 1 (Baseline) 대비: {test_acc:.2f}% -> {test_acc4:.2f}% ({diff1:+.2f}%p)")

# 2. Cleaning(2차)과 비교
if 'test_acc2' in globals():
    diff2 = test_acc4 - test_acc2
    print(f"Step 2 (Cleaning) 대비: {test_acc2:.2f}% -> {test_acc4:.2f}% ({diff2:+.2f}%p)")

# 3. Fine-tuning(3차)과 비교
if 'test_acc3' in globals():
    diff3 = test_acc4 - test_acc3
    print(f"Step 3 (Fine-tuning) 대비: {test_acc3:.2f}% -> {test_acc4:.2f}% ({diff3:+.2f}%p)")

    if diff3 > 0:
        print("Augmentation(데이터 증강) 효과로 성능이 정점을 찍었습니다!")
    elif diff3 == 0:
        print("성능 변화가 없습니다. (이미 모델이 한계치에 도달했을 수 있음)")
    else:
        print("성능이 소폭 하락했습니다.")
        print("(이유: Augmentation으로 학습이 어려워졌거나, Step 3가 운 좋게 Test셋에 더 잘 맞았을 수 있음)")
        print("하지만 모델의 일반화(Robustness) 능력은 Step 4가 더 뛰어날 가능성이 높습니다.")

# 1. Step 4 모델 로드
weights_path = 'best_finetuned_model_v4.pth'
model.load_state_dict(torch.load(weights_path))
model.to(device)
model.eval()

print(f"최종 v4 모델(Augmentation 적용) 로드 완료")

# 2. 예측 수행
all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in dataloaders['test']:
        inputs = inputs.to(device)
        labels = labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# 3. Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Final Confusion Matrix (Step 4: Robust Model)', fontsize=12, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# 4. 리포트 출력
print("\n=== [Step 4] Final Classification Report ===")
print(classification_report(all_labels, all_preds, target_names=class_names, digits=4))

import math
import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

def visualize_many_gradcams(model, dataloader, class_names, target_label, num_samples=24):
    """
    특정 클래스의 정답 이미지들을 많이(num_samples) 뽑아서 그리드로 보여주는 함수
    """
    print(f"'{target_label}' 클래스 대량 시각화 중... (목표: {num_samples}장)")

    model.eval()
    target_layers = [model.features[-1]]
    cam = GradCAM(model=model, target_layers=target_layers)

    target_idx = class_names.index(target_label)

    collected_images = []

    # 1. 데이터 수집 (배치 순회)
    for inputs, labels in dataloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        # 정답인 케이스만 수집
        for i in range(inputs.size(0)):
            if labels[i].item() == target_idx and preds[i].item() == target_idx:
                collected_images.append(inputs[i].cpu())

                if len(collected_images) >= num_samples:
                    break
        if len(collected_images) >= num_samples:
            break

    # 데이터가 부족할 경우 처리
    if len(collected_images) == 0:
        print("해당 클래스의 정답 샘플을 찾지 못했습니다.")
        return

    # 2. 그리드 그리기
    cols = 3  # 한 줄에 6장씩
    rows = math.ceil(len(collected_images) / cols)

    plt.figure(figsize=(10, 3.5 * rows))

    for i, img_tensor in enumerate(collected_images):
        # Grad-CAM 계산
        input_tensor = img_tensor.unsqueeze(0).to(device)
        grayscale_cam = cam(input_tensor=input_tensor, targets=None)[0, :]

        # 이미지 변환 (Denormalization)
        rgb_img = img_tensor.numpy().transpose((1, 2, 0))
        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        rgb_img = std * rgb_img + mean
        rgb_img = np.clip(rgb_img, 0, 1)
        rgb_img = np.float32(rgb_img)

        # 히트맵 적용
        visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

        ax = plt.subplot(rows, cols, i + 1)
        plt.imshow(visualization)
        plt.axis('off')

    plt.suptitle(f"Consistency Check: {target_label} ({len(collected_images)} Samples)", fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

# ================= 실행 =================

# 1. Buildings (건물) 일관성 체크 (24장)
# 기대 결과: 건물의 '벽면'이나 '창문'을 보는지 확인 (도로나 하늘 X)
visualize_many_gradcams(model, dataloaders['test'], class_names, target_label='buildings', num_samples=6)

# 2. Street (거리) 일관성 체크 (24장)
# 기대 결과: '도로 바닥'이나 '소실점(도로 끝)'을 보는지 확인
visualize_many_gradcams(model, dataloaders['test'], class_names, target_label='street', num_samples=6)

# 3. Culture (문화재) 일관성 체크 (24장)
# 기대 결과: 대부분의 사진에서 '나무'가 아닌 '건축물(기와, 탑)'에 붉은색이 들어와야 함
visualize_many_gradcams(model, dataloaders['test'], class_names, target_label='culture', num_samples=6)

# 4. Parks (공원) 일관성 체크 (24장)
visualize_many_gradcams(model, dataloaders['test'], class_names, target_label='parks', num_samples=6)

# 모델 저장 경로 설정 (구글 드라이브 권장)
save_path = '/content/drive/MyDrive/efficientnet_v2_final.pth'

# 모델의 가중치(weight) 저장
torch.save(model.state_dict(), save_path)

print(f"모델 저장 완료: {save_path}")